import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {randomUUID} from 'node:crypto';
import {getStagedArticleFigures} from '../cloudflare/worker/src/local-captures.js';
const source=fs.readFileSync('public/toc-mainline.user.js','utf8'),P='osg-toc-v6:',EPOCH=1790082000000;
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log('MISSING_ONLY_PASS '+name)};
const article=(n,extra={})=>({doi:'10.1021/jacs.6c'+String(n).padStart(5,'0'),journal:'JACS',addedDate:'2026-10-02',date:'2026-10-01',...extra});
const fig=(doi,n)=>({label:'Figure '+n,sourceUrl:'https://acs.silverchair-cdn.com/10.1021_'+doi.split('/')[1]+'/f'+n+'.png',contentHash:'a'.repeat(32),width:1000,height:500,quality:'high'});
const queue=articles=>({articles,latestAddedDate:'2026-10-02',generatedAt:'2026-10-02T10:00:00Z',webpageDoiCount:articles.length,mediaGeneration:EPOCH});
const inv=articles=>({media:{items:articles.map(a=>({doi:a.doi,tocStored:true,figureCount:2,usableFigureCount:2,capturedFigures:[fig(a.doi,1),fig(a.doi,2)]}))},tocs:{count:0,items:[]},figures:{schemaVersion:'capture-inventory-v1',complete:true,count:articles.length,items:articles.map(a=>({doi:a.doi,expectedFigureCount:2,figures:{}}))},evidence:{count:articles.length,items:articles.map(a=>({doi:a.doi,available:true,evidenceLevel:'partial'}))},errors:[]});
function h(q=queue([]),inventory=inv([]),opts={}){
 const store=new Map(),opened=[],calls=[],timers=new Map();let now=EPOCH+12*86400000,id=0;
 class D extends Date{constructor(...args){super(...(args.length?args:[now]))}static now(){return now}}
 const get=u=>{calls.push(u);if(u.includes('capture-capabilities'))return {captureVersion:'6.2.20',mediaControllerRevision:'2.2.39',mediaGeneration:EPOCH,evidenceSchemaVersion:'article-evidence-v2',mode:'verified-staging'};
  if(u.includes('toc-demand'))return q;if(u.includes('local-capture-index'))return inventory.tocs;if(u.includes('/staged?'))return inventory.figures;throw Error('unexpected get '+u)};
 const ctx=vm.createContext({console,Date:D,URL,Map,Set,document:{},crypto:{randomUUID},location:{hostname:'gallery.gczhouwld.com',pathname:'/',href:'https://gallery.gczhouwld.com/',hash:''},window:{open(){},close(){},alert(){},prompt(){return null}},
 GM_getValue:(k,d)=>store.has(k)?structuredClone(store.get(k)):d,GM_setValue:(k,v)=>store.set(k,structuredClone(v)),GM_deleteValue:k=>store.delete(k),GM_listValues:()=>[...store.keys()],GM_registerMenuCommand(){},
 setTimeout:(f,ms)=>{timers.set(++id,{f,ms});return id},clearTimeout:i=>timers.delete(i),setInterval:(f,ms)=>{timers.set(++id,{f,ms,interval:true});return id},clearInterval:i=>timers.delete(i),
 __get:async u=>opts.get?opts.get(u,get):get(u),__post:async(u,p)=>{calls.push(u);if(opts.post)return opts.post(u,p);return {items:inventory.media.items.filter(x=>p.dois.includes(x.doi))}},__private:async()=>{if(opts.evidenceError)throw Error('private_http_401');return inventory.evidence},__sleep:async ms=>{now+=ms},
 GM_openInTab:u=>{const j=store.get(P+'active-job');opened.push(structuredClone(j));if(!opts.noResult)store.set(P+'result:'+j.doi,{doi:j.doi,jobId:j.jobId,version:'6.2.20',finishedAt:new D().toISOString(),status:'success',toc:{status:j.captureToc?'stored':'already_available'},fulltext:{status:opts.failText?'failed':j.captureEvidence?'stored':'not_requested'}});return {closed:false,close(){this.closed=true}};}
 });
 const cut=source.lastIndexOf('  installManualRestartListener();');
 vm.runInContext(source.slice(0,cut)+`
 isGalleryPage=()=>true;writeToken=()=> 'fixture';badge=()=>{};sleep=__sleep;getJson=__get;postReadJson=__post;getPrivateJson=__private;enqueueCaptureReport=()=>true;
 function fixtureMembership(q){var dois=q.articles.map(a=>normalizeDoi(a.doi));return {ok:true,revision:'fixture-active-v2',publicationSlot:'2026-10-02T08:00:00+08:00',catalogId:'a'.repeat(64),asOfDate:'2026-10-02',cutoff:'2026-07-02',memberCount:dois.length,activeCount:dois.length,hotCount:dois.length,archiveCount:0,recentAdditionCount:0,activeDois:dois,archiveDois:[],memberDois:dois,withdrawn:[]};}
 observeArchitectureMembership=async(q)=>fixtureMembership(q);
 async function fixtureReadMissing(q){var fixtureInventoryRun={id:'fixture-inventory',summary:{results:[]},inventoryCache:new Map(),activeDois:new Set(fixtureMembership(q).activeDois)};var prior=manualExecutionCurrent;manualExecutionCurrent=()=>true;try{return await readMissingCaptureInventory(q,fixtureInventoryRun);}finally{manualExecutionCurrent=prior;}}
 globalThis.shellFixture=()=>{assertBoundCaptureJob=()=>true;pageState=()=>({shell:true,auth:false,challenge:false});collectCandidates=()=>[];collectArticleFigureCandidates=()=>[];captureLiveUpdate=()=>true;};
 globalThis.bodyFixture=()=>{assertBoundCaptureJob=()=>true;captureLiveUpdate=()=>true;pushTrace=()=>true;waitForPairedVisuals=async()=>({toc:[],figures:__figs});globalThis.__downloads=0;acquireBestVisual=async(j,c)=>{__downloads++;return{candidate:c[0],image:{width:1000,height:500},quality:{quality:'high'}}};uploadArticleFigure=async()=>({contentHash:'a'.repeat(32)});tryCaptureArticleEvidence=async()=>({status:'not_requested'});finishPairedJob=async(j,r)=>r;};
 globalThis.T={buildMissingCaptureJobs,captureNeedText,captureLiveText,captureLiveSnapshot,forceStartFromHead,manualRunBlocksAutomatic,readMissingCaptureInventory,checkpointKey,waitForPairedVisuals,runPublisherJob,fixtureMembership};
 })();`,ctx);
 return {T:ctx.T,ctx,store,opened,calls,timers,plan:(ar=q.articles,i=inventory)=>{const qq=queue(ar),m=ctx.T.fixtureMembership(qq),run={id:'test',summary:{results:[]},activeDois:new Set(m.activeDois)};return {jobs:Array.from(ctx.T.buildMissingCaptureJobs(qq,run,i)),summary:run.summary};}};
}
const three=[article(1),article(2),article(3)];
await test('765 complete records do not become a 765-paper queue',()=>{const ar=Array.from({length:765},(_,i)=>article(i));const i=inv(ar);i.media.items[1].tocStored=false;i.figures.items[2].expectedFigureCount=3;i.evidence.items.splice(3,1);i.evidence.count--;const x=h(queue(ar),i).plan();assert.equal(x.jobs.length,3);assert.equal(x.summary.inventoryUnknown,0)});
await test('only TOC missing sets only TOC flag',()=>{const i=inv(three);i.media.items[0].tocStored=false;const j=h(queue(three),i).plan().jobs[0];assert.deepEqual([j.captureToc,j.captureFigures,j.captureEvidence],[true,false,false])});
await test('partial body figure inventory counts missing labels',()=>{const i=inv(three);i.figures.items[0].expectedFigureCount=5;const j=h(queue(three),i).plan().jobs[0];assert.deepEqual([j.captureToc,j.captureFigures,j.captureEvidence,j.missingFigureCount],[false,true,false,3]);assert.match(h().T.captureNeedText(j),/缺 3 张/)});
await test('missing text only requests text',()=>{const i=inv(three);i.evidence.items=[];const jobs=h(queue(three),i).plan().jobs;assert.equal(jobs.length,3);assert.ok(jobs.every(j=>!j.captureToc&&!j.captureFigures&&j.captureEvidence))});
await test('stored partial or abstract text is labelled honestly, not recaptured endlessly',()=>{const i=inv(three);i.evidence.items[0].evidenceLevel='abstract_only';assert.equal(h(queue(three),i).plan().jobs.length,0);const x=h();const t=x.T.captureLiveText({active:true,activeJob:{existingEvidenceLevel:'abstract_only'},remainingNeeds:{},inventoryErrors:[]});assert.match(t.evidence,/仅摘要/);assert.doesNotMatch(t.evidence,/完整正文/)});
await test('R2-staged complete media pending publication is not missing acquisition',()=>{const ar=[article(1)],i=inv(ar);i.media.items[0]={doi:ar[0].doi,tocStored:false,figureCount:0,capturedFigures:[]};i.tocs.items=[{doi:ar[0].doi,mediaGeneration:EPOCH,kind:'official',imageUrl:'https://api.gczhouwld.com/media/x',contentHash:'a'.repeat(32)}];i.figures.items[0].figures={'Figure 1':fig(ar[0].doi,1),'Figure 2':fig(ar[0].doi,2)};assert.equal(h(queue(ar),i).plan().jobs.length,0)});
await test('19 of30 saved leads to11 missing, not thirty redownloads',()=>{const ar=[article(1)],i=inv(ar);i.media.items[0].capturedFigures=[];i.media.items[0].figureCount=0;i.figures.items[0].expectedFigureCount=30;i.figures.items[0].figures=Object.fromEntries(Array.from({length:19},(_,n)=>{const f=fig(ar[0].doi,n+1);return[f.label,f]}));const j=h(queue(ar),i).plan().jobs[0];assert.equal(j.missingFigureCount,11);assert.equal(Object.keys(j.capturedFigures).length,19);assert.equal(j.recaptureFromHead,false)});
await test('production and stage label union recognizes disjoint completed figures',()=>{const ar=[article(1)],i=inv(ar);i.figures.items[0].expectedFigureCount=3;i.figures.items[0].figures={'Figure 3':fig(ar[0].doi,3)};assert.equal(h(queue(ar),i).plan().jobs.length,0)});
await test('same label never counts twice across storage layers',()=>{const ar=[article(1)],i=inv(ar);i.figures.items[0].expectedFigureCount=3;i.figures.items[0].figures={'Figure 1':fig(ar[0].doi,1)};assert.equal(h(queue(ar),i).plan().jobs[0].missingFigureCount,1)});
await test('old generation TOC never removes current TOC gap',()=>{const i=inv(three);i.media.items[0].tocStored=false;i.tocs.items=[{doi:three[0].doi,mediaGeneration:0,kind:'official',imageUrl:'x',contentHash:'abc'}];assert.equal(h(queue(three),i).plan().jobs.length,1)});
await test('Figure1 is never mislabelled official TOC',()=>{const i=inv(three);i.media.items[0].tocStored=false;i.media.items[0].primaryKind='figure1';const j=h(queue(three),i).plan().jobs[0];assert.equal(j.captureToc,true);assert.match(h().T.captureNeedText(j),/官方 TOC.*Figure 1/)});
await test('nonzero count without complete observation is queued for discovery, never presumed complete',()=>{const i=inv(three);i.figures.items[0].expectedFigureCount=0;const x=h(queue(three),i).plan();assert.equal(x.jobs.length,1);assert.equal(x.jobs[0].captureFigures,true);assert.equal(x.jobs[0].figureCoverageUnconfirmed,true);assert.equal(Object.keys(x.jobs[0].capturedFigures).length,2);assert.equal(x.summary.inventoryUnknown,0)});
await test('unreadable inventory is unknown and never converted to全站缺失',()=>{const x=h().plan(three,{errors:['offline']});assert.equal(x.jobs.length,0);assert.equal(x.summary.inventoryUnknown,3)});
await test('evidence401 does not turn every existing text into缺全文',async()=>{const x=h(queue(three),inv(three),{evidenceError:true});const i=await x.T.readMissingCaptureInventory(queue(three));const p=x.plan(three,i);assert.equal(p.jobs.length,0);assert.equal(p.summary.inventoryUnknownLayers.evidence,3);assert.ok(i.errors[0].includes('401'))});
await test('every batch sorted before journal, not just latest cohort',()=>{const ar=[article(1,{journal:'Nature',addedDate:'2026-09-28'}),article(2,{journal:'Organic Letters',addedDate:'2026-10-01'}),article(3,{journal:'Angew',addedDate:'2026-09-30'})],i=inv(ar);i.evidence.items=[];assert.deepEqual(h(queue(ar),i).plan().jobs.map(j=>j.doi),[ar[1].doi,ar[2].doi,ar[0].doi])});
await test('same-batch Nature Science Nature-sub Science-sub JACS Angew Chem order',()=>{const names=['Chem','Angew','JACS','Science Advances','Nature Catalysis','Science','Nature'],ar=names.map((journal,n)=>article(n,{journal})),i=inv(ar);i.evidence.items=[];assert.deepEqual(h(queue(ar),i).plan().jobs.map(j=>j.journal),names.reverse())});
await test('removed DOI in stale inventory never enters the queue',()=>{const i=inv(three);i.evidence.items=[];assert.equal(h().plan([three[0]],i).jobs.length,1)});
await test('invalid registry duplicate is rejected',()=>{assert.throws(()=>h().plan([three[0],three[0]],inv(three)),/duplicate/)});
await test('immediate click revokes lock synchronously and starts inventory without polling',async()=>{const i=inv(three);i.evidence.items=[];i.evidence.count=0;const x=h(queue(three),i);x.store.set(P+'controller-lease',{owner:'foreign',expiresAt:Date.now()+9e5});x.store.set(P+'active-job',{jobId:'old'});const p=x.T.forceStartFromHead();assert.equal(x.store.has(P+'active-job'),false);assert.match(x.store.get(P+'controller-lease').owner,/manual:/);assert.equal([...x.timers.values()].filter(t=>!t.interval).length,0);await p;assert.equal(x.opened.length,3);assert.equal(x.store.get(P+'last-run-summary').total,3)});
await test('complete inventory ends at zero pending without opening a publisher',async()=>{const x=h(queue(three),inv(three));await x.T.forceStartFromHead();assert.equal(x.opened.length,0);assert.equal(x.store.get(P+'last-run-summary').total,0);assert.equal(x.T.manualRunBlocksAutomatic(),true)});
await test('requested text failure is partial, not false task success',async()=>{const i=inv(three);i.evidence.items=[];i.evidence.count=0;const x=h(queue(three),i,{failText:true});await x.T.forceStartFromHead();assert.equal(x.store.get(P+'last-run-summary').partial,3)});
await test('new panel shows actual missing layer and no whole-corpus denominator while starting',()=>{const x=h();const t=x.T.captureLiveText({missingOnly:true,phase:'starting',active:false,total:765,completed:0,remainingNeeds:{},inventoryErrors:[]});assert.doesNotMatch(t.batch,/765/);assert.match(t.gaps,/库存/)});
await test('production request coverage mismatch is unknown not zero assets',async()=>{const x=h(queue(three),inv(three),{post:()=>({items:[]})});const i=await x.T.readMissingCaptureInventory(queue(three));assert.equal(i.media.items.length,0);assert.ok(i.errors.some(x=>x.includes('媒体库存')))});
await test('phase identifies unloaded shell rather than false no-picture conclusion',async()=>{const x=h();x.ctx.shellFixture();await assert.rejects(x.T.waitForPairedVisuals({captureToc:true,captureFigures:true,captureDeadline:EPOCH+20*86400000},[]),/publisher_page_not_ready/)});
await test('publisher body capture reuses19 proven figures and downloads only11',async()=>{const a=article(1),x=h();x.ctx.__figs=Array.from({length:30},(_,n)=>({label:'Figure '+(n+1),url:fig(a.doi,n+1).sourceUrl}));x.ctx.bodyFixture();
 const saved=Object.fromEntries(Array.from({length:19},(_,n)=>{const f=fig(a.doi,n+1);return[f.label,f]}));const r=await x.T.runPublisherJob({...a,jobId:'x',captureVersion:'6.2.20',missingOnly:true,recaptureFromHead:false,captureToc:false,captureFigures:true,captureEvidence:false,capturedFigures:saved});assert.equal(x.ctx.__downloads,11);assert.equal(r.figures.stored,30);assert.equal(r.figuresStaged,11)});
const req=new Request('https://api.gczhouwld.com/api/article-figures/staged?inventory=1');
function env(stage,reports,corrupt=false){const m=new Map([['local-captures/article-figures/stage-index.json',corrupt?'not json':JSON.stringify({items:stage})],['local-captures/tampermonkey/report-index.json',JSON.stringify({items:reports})]]);return {MEDIA:{get:async k=>m.has(k)?{text:async()=>m.get(k)}:null}};}
const entry=(n,label=1)=>{const d=article(n).doi;return {doi:d,pageDoi:d,captureVersion:'6.2.20',mediaGeneration:EPOCH,updatedAt:EPOCH+1000,r2Key:'local-captures/article-figures/images/'+n+'.png',...fig(d,label)}};
await test('compact stage mode includes more than2000 current figures without truncation',async()=>{const stage=Object.fromEntries(Array.from({length:2005},(_,n)=>['id'+n,entry(n)]));const r=await getStagedArticleFigures(req,env(stage,{}));assert.equal(r.status,200);assert.equal(r.body.count,2005);assert.equal(r.body.complete,true)});
await test('compact stage mode filters cross-DOI old-generation and low-quality records',async()=>{const a=entry(1),b={...entry(2),sourceUrl:fig(article(999).doi,1).sourceUrl},c={...entry(3),mediaGeneration:0},d={...entry(4),width:100,height:80};const r=await getStagedArticleFigures(req,env({a,b,c,d},{}));assert.equal(r.body.count,1)});
await test('new empty-page report cannot erase previously observed30-figure expectation',async()=>{const d=article(1).doi;const r=await getStagedArticleFigures(req,env({}, {d:{doi:d,final:true,captureVersion:'6.2.20',mediaNeed:'figures',updatedAt:EPOCH+1000,figuresDiscovered:0,attempts:[{doi:d,final:true,captureVersion:'6.2.20',mediaNeed:'figures',updatedAt:EPOCH+900,figuresDiscovered:30}]}}));assert.equal(r.body.items[0].expectedFigureCount,30)});
await test('corrupted R2 index produces503 rather than all papers missing',async()=>{const r=await getStagedArticleFigures(req,env({}, {},true));assert.equal(r.status,503);assert.equal(r.body.error,'capture_inventory_unavailable')});
console.log(JSON.stringify({passed,mode:'missing-only-v4',productionWrites:0,realPublisherRequests:0}));
